# ──────────────────────────────
# Global values
# ──────────────────────────────
global:
  domain: auth.estebanmf.space


# ──────────────────────────────
# Namespaces
# ──────────────────────────────
namespaces:
  argocd: argocd
  certManager: cert-manager
  ingress: ingress-nginx
  zitadel: auth


# ──────────────────────────────
# Cert-manager subchart
# ──────────────────────────────
certManager:
  enabled: true
  installCRDs: true

# ClusterIssuer values for your custom template (10-clusterissuer-cloudflare.yaml)
letsencrypt:
  clusterIssuerName: letsencrypt-cloudflare
  email: you@example.com                # 👈 replace with your real email
  cloudflareAPITokenSecretName: cloudflare-api-token-secret
  cloudflareAPITokenKey: api-token

# ──────────────────────────────
# Ingress-nginx subchart
# ──────────────────────────────
ingressNginx:
  enabled: true
  controller:
    service:
      annotations: {}   # add DigitalOcean LB annotations if needed

# ──────────────────────────────
# ZITADEL subchart
# ──────────────────────────────
zitadel:
  enabled: true
  fullnameOverride: "zitadel"

  # 👇 forward the global domain so Zitadel chart doesn’t error
  global:
    domain: auth.estebanmf.space

  zitadel:
    masterkeySecretName: "zitadel-masterkey"
    configmapConfig:
      ExternalDomain: "auth.estebanmf.space"
      ExternalPort: 443
      ExternalSecure: true
      TLS:
        Enabled: true
    secretConfig:
      TLS:
        existingSecret: "zitadel-internal-tls"
        certKey: "tls.crt"
        keyKey: "tls.key"

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    hosts:
      - host: auth.estebanmf.space
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: auth-estebanmf-space-tls
        hosts:
          - auth.estebanmf.space

  login:
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cloudflare
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      hosts:
        - host: auth.estebanmf.space
          paths:
            - path: /ui/v2/login
              pathType: Prefix
      tls:
        - secretName: auth-estebanmf-space-tls
          hosts:
            - auth.estebanmf.space

# ──────────────────────────────
# Dev placeholders
# ──────────────────────────────
_dev:
  generateDummyZitadelSecrets: false

