global:
  domain: auth.estebanmf.space

namespaces:
  kubeAuth: auth

certManager:
  email: estebanmff@gmail.com
  clusterIssuerName: letsencrypt-cloudflare
  cloudflareAPITokenSecretName: cloudflare-api-token-secret
  cloudflareAPITokenKey: api-token

postgresql:
  enabled: true
  auth:
    username: zitadel
    password: zitadelpass
    database: zitadel
  primary:
    persistence:
      enabled: true

