apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.letsencrypt.clusterIssuerName }}
spec:
  acme:
    email: {{ .Values.letsencrypt.email | quote }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ printf "%s-account-key" .Values.letsencrypt.clusterIssuerName }}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{ .Values.letsencrypt.cloudflareAPITokenSecretName }}
              key: {{ .Values.letsencrypt.cloudflareAPITokenKey }}

