apiVersion: apps/v1
kind: Deployment
metadata:
  name: zitadel
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zitadel
  template:
    metadata:
      labels:
        app: zitadel
    spec:
      containers:
      - name: zitadel
        image: ghcr.io/zitadel/zitadel:latest
        args: ["start-from-init"]
        env:
        - name: ZITADEL_MASTERKEY
          valueFrom:
            secretKeyRef:
              name: zitadel-masterkey
              key: masterkey
        - name: ZITADEL_DATABASE_POSTGRES_HOST
          value: "kube-auth-postgresql"
        - name: ZITADEL_DATABASE_POSTGRES_PORT
          value: "5432"
        - name: ZITADEL_DATABASE_POSTGRES_USER
          value: "zitadel"
        - name: ZITADEL_DATABASE_POSTGRES_PASSWORD
          value: "zitadelpass"
        - name: ZITADEL_DATABASE_POSTGRES_DATABASE
          value: "zitadel"
        - name: ZITADEL_EXTERNALDOMAIN
          value: "auth.estebanmf.space"
        - name: ZITADEL_EXTERNALPORT
          value: "443"
        - name: ZITADEL_EXTERNALSECURE
          value: "true"
        ports:
        - containerPort: 8080
        - containerPort: 8443

