apiVersion: v1
kind: Service
metadata:
  name: zitadel
  namespace: {{ include "kube-auth.ns" . }}
spec:
  type: ClusterIP
  selector:
    app: zitadel
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443

