apiVersion: v1
kind: Service
metadata:
  name: zitadel
  namespace: {{ .Values.namespaces.kubeAuth }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: zitadel

