apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EstebanForero/kube-auth.git
    targetRevision: master
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

